module.exports = [
  "strapi::errors",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "default-src": ["none"],
          "connect-src": [
            "'self'",
            "https:",
            "*.tinymce.com",
            "*.tiny.cloud",
            "blob:",
          ],
          "font-src": ["'self'", "*.tinymce.com", "*.tiny.cloud"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "dl.airtable.com",
            "res.cloudinary.com",
            "*.tinymce.com",
            "*.tiny.cloud",
            "data:",
            "blob:",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "dl.airtable.com",
            "res.cloudinary.com",
          ],
          "script-src": ["'self'", "*.tinymce.com", "*.tiny.cloud"],
          "style-src": [
            "'self'",
            "'unsafe-inline'",
            "*.tinymce.com",
            "*.tiny.cloud",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];
